### ISSUE TITLE
pypump-shell --help should show something about needing a webfinger

### ISSUE THREAD

**Issue by Simonft** [xray7224/PyPump#123]
Running pypump-shell shows "You must specify a webfinger", but it's unclear where you would do this and --help makes no reference to any positional arguments.

**Comment by xray7224** [comment]
We ought to switch over to argparse, this actually automatically provides this and is the modern python equiverlent to optparse (currently what we use).

**Comment by Simonft** [comment]
If you don't care about it being in stdlib, http://docopt.org/  is awesome. I may give this a shot.
