### ISSUE TITLE
TypeError: ...  is not JSON serializable

### ISSUE THREAD

**Issue by polypmer** [xray7224/PyPump#127]
I am following the tutorial and it goes swimmingly using python 2 but when I try it using python 3 I get variations of this:
`TypeError: b'tuXTMOsWY9_vLtg3V6k-Dg' is not JSON serializable` 
after I try making the PyPump class
 `pump = PyPump(client=client, verifier_callback=simple_verifier)`

This is the full error I get:
<pre>
TypeError                                 Traceback (most recent call last)
<ipython-input-17-a213311858db> in <module>()
----> 1 pump = PyPump(client=client, verifier_callback=simple_verifier)

/usr/lib/python3.4/site-packages/pypump/pypump.py in __init__(self, client, verifier_callback, store, callback, verify_requests, retries, timeout)
    129         if "oauth-request-token" not in self.store and "oauth-access-token" not in self.store:
    130             # we Need to make a new oauth request
--> 131             self.oauth_request()
    132 
    133     @property

/usr/lib/python3.4/site-packages/pypump/pypump.py in oauth_request(self)
    378         self._server_tokens = self.request_token()
    379 
--> 380         self.store["oauth-request-token"] = self._server_tokens["token"]
    381         self.store["oauth-request-secret"] = self._server_tokens["token_secret"]
    382 

/usr/lib/python3.4/site-packages/pypump/store.py in __setitem__(self, key, *args, **kwargs)
     77         key = self.__prefix_key(key)
     78         super(AbstractStore, self).__setitem__(key, *args, **kwargs)
---> 79         self.save()
     80 
     81     def __getitem__(self, key, *args, **kwargs):

/usr/lib/python3.4/site-packages/pypump/store.py in save(self)
    166         fd = os.open(filename, os.O_WRONLY | os.O_CREAT, mode)
    167         fout = os.fdopen(fd, "w")
--> 168         fout.write(json.dumps(self.export()))
    169         fout.close()
    170 

/usr/lib/python3.4/json/__init__.py in dumps(obj, skipkeys, ensure_ascii, check_circular, allow_nan, cls, indent, separators, default, sort_keys, **kw)
    228         cls is None and indent is None and separators is None and
    229         default is None and not sort_keys and not kw):
--> 230         return _default_encoder.encode(obj)
    231     if cls is None:
    232         cls = JSONEncoder

/usr/lib/python3.4/json/encoder.py in encode(self, o)
    190         # exceptions aren't as detailed.  The list call should be roughly
    191         # equivalent to the PySequence_Fast that ''.join() would do.
--> 192         chunks = self.iterencode(o, _one_shot=True)
    193         if not isinstance(chunks, (list, tuple)):
    194             chunks = list(chunks)

/usr/lib/python3.4/json/encoder.py in iterencode(self, o, _one_shot)
    248                 self.key_separator, self.item_separator, self.sort_keys,
    249                 self.skipkeys, _one_shot)
--> 250         return _iterencode(o, 0)
    251 
    252 def _make_iterencode(markers, _default, _encoder, _indent, _floatstr,

/usr/lib/python3.4/json/encoder.py in default(self, o)
    171 
    172         """
--> 173         raise TypeError(repr(o) + " is not JSON serializable")
    174 
    175     def encode(self, o):

TypeError: b'tuXTMOsWY9_vLtg3V6k-Dg' is not JSON serializable</pre>

(I am following the tutorial and/or the Quick'nDirty instructions verbatim using both first ipython notebooks and then strictly ipython (which does work with python 2)).

**Comment by polypmer** [comment]
It might very well be something off with my environment (I'm not too careful-precise about setting it up). Would it help if I pasted my credentials.json file? Or would that be a terribly insecure-silly thing to do?

**Comment by xray7224** [comment]
It's not your environment, I am also able to reproduce it.

**PSA**: Don't ever post your credentials file, whilst technically revokable (pump.io doesn't actually provide you with a mechanism to do that), they give anyone with them full access to your account.

**Comment by polypmer** [comment]
Yay! I can use py3!!

**Comment by dper** [comment]
I'm using PyPump as a library in PumpTweet, and this bug impacts adding new Pump accounts in a big way. It was not fixed in 0.6 (the most recent release) but is fixed in master. Is there a chance of some kind of release, whether that be 0.6.1 (e.g. master right now) or 0.7 (if the development has progressed to your goals), so that I can update the dependencies accordingly?

Thanks for any information you can provide. :-)

The workaround for people depending on releases is to install both Python2 and Python3, first use Python2 for logging in the first time, and subsequently use Python3. Or to only use Python2.

**Comment by moggers87** [comment]
I don't know what's happened since 0.6 (e.g. some of our API may have changed?), so I wouldn't want to do 0.6.1 based on master.

I suggest opening a separate issue for a 0.6.1 release if you think it's worth this one bugfix.

**Comment by kabniel** [comment]
0.6 is over a year old so i think we should do a 0.7 soon just to get the changes packaged.

**Comment by dper** [comment]
@moggers87 No need for 0.6.1. Simple enough for me to use 0.7 when it comes out.

Thanks for the quick replies, everyone!
