### ISSUE TITLE
ssl modules for py 2 not mentioned in pypump.org docs

### ISSUE THREAD

**Issue by kabniel** [xray7224/PyPump#130]
recommended install of additional modules for SSL/SNI support in Py2 (see https://github.com/xray7224/PyPump#installation) is not mentioned in pypump.org docs, we should add it to install section

**Comment by profOnno** [comment]
indeed... 
found the some documentation about the problem.
https://www.happyassassin.net/2015/03/31/ssl-certificate-issues-with-reverse-proxy-subdomains-when-using-python-requests-with-python-2-7-9/

After :
```
sudo pip install requests[security]
sudo pip install pyOpenSSL
sudo pip install pyasn1
sudo pip install ndg-httpsclient
```
re-build
`sudo pip --editable --upgrade .`

Now i can use p to authorize
still get :
`[Error] Something has gone wrong :(`

but p accounts is happy and i can post a note

**Comment by moggers87** [comment]
As 2.7.9 has backported SNI support, we might consider closing this and removing the warning from `setup.py`

See http://docs.python-requests.org/en/master/community/faq/#what-are-hostname-doesn-t-match-errors
