### ISSUE TITLE
RTD not showing v0.6

### ISSUE THREAD

**Issue by moggers87** [xray7224/PyPump#135]
https://readthedocs.org/projects/pypump/ doesn't list v0.6, I guess it needs some manual poking first?

**Comment by kabniel** [comment]
On http://pypump.readthedocs.io/en/stable/ the "Edit on Github" link points to https://github.com/xray7224/PyPump/blob/6b612a7ed3c5a9b0a0190f3999fcddb851d1900f/docs/index.rst which is the same commit as 0.6 https://github.com/xray7224/PyPump/commits/v0.6

**Comment by moggers87** [comment]
Superseded by #155
