### ISSUE TITLE
Version bump from 0.6

### ISSUE THREAD

**Issue by craigmaloney** [xray7224/PyPump#137]
I installed the latest version of p from github and got the following:

```craig@lister:~/Downloads$ p inbox
Traceback (most recent call last):
  File "/home/craig/.virtualenvs/p/bin/p", line 28, in <module>
    from pypump.models.media import (Image, Video, Audio)
ImportError: No module named media
```

Not sure when media was added but the version I had prior wasn't getting updated automatically.

**Comment by moggers87** [comment]
p needs to update its documentation and/or requires.

You can install the latest PyPump from git via this command:

```
pip install -e git+https://github.com/xray7224/PyPump.git#egg=pypump
```
