### ISSUE TITLE
KeyError: 'activity-outbox'

### ISSUE THREAD

**Issue by strugee** [xray7224/PyPump#138]
I have an installation of PumpTweet, and when I run it, it spits out the following error:

```
 % ./pt.sh
Reading the config file...
Logging into the Pump server...
Logging into Twitter...
Looking at Pump outbox activity...
Traceback (most recent call last):
  File "./pt.py", line 18, in <module>
    pumptweet.pull_and_push()
  File "/home/alex/pumptweet_community/pumptweet/PumpTweet.py", line 156, in pull_and_push
    notes = self.get_new_activities()
  File "/home/alex/pumptweet_community/pumptweet/PumpTweet.py", line 42, in get_new_activities
    outbox = self.pump_me.outbox
  File "/home/alex/pumptweet/local/lib/python2.7/site-packages/pypump/models/person.py", line 67, in outbox
    self._outbox = self._outbox or Outbox(self.links['activity-outbox'], pypump=self._pump)
KeyError: 'activity-outbox'
```

Some additional information:

```
 % pip list
argparse (1.2.1)
BeautifulSoup (3.2.1)
ndg-httpsclient (0.4.0)
oauthlib (1.0.3)
pip (1.5.6)
pyasn1 (0.1.8)
pyOpenSSL (0.15.1)
PyPump (0.6)
python-dateutil (2.4.2)
python-twitter (2.2)
requests (2.8.1)
requests-oauthlib (0.5.0)
setuptools (5.5.1)
six (1.9.0)
wsgiref (0.1.2)

% git rev-parse HEAD
f44f0b896c37840cd29750662ffeb6c62354cdea
```

**Comment by dper** [comment]
This could quite possibly be a bug in PumpTweet.  I haven't looked at it enough to be sure.

**Comment by strugee** [comment]
It's worth noting that I can't quite nail down what changed (e.g. a Git pull, a PyPump upgrade, etc.). This kind of just appeared one day 

@dper thanks for chiming in!

**Comment by strugee** [comment]
The relevant Pump server is down currently. Could that be the issue?

**Comment by dper** [comment]
@strugee Yes I think so. This is probably PumpTweet's issue. When the pump server is down it should give up earlier and show a more informative error message. We'll know for sure when `microca.st` gets back up. I get the same message as you. Bug opened on the PumpTweet page.

**Comment by strugee** [comment]
@dper great, thanks. Does that mean this issue should be closed?

**Comment by dper** [comment]
Yes, I think it can be closed.  If my explanation is wrong, we'll find 
out once microca.st is up again and can re-open the bug if need be.

**Comment by strugee** [comment]
Great.

**Comment by stephensekula** [comment]
I have a problem whose symptom is the same as @strugee, but which is not solved by the above problem (the pump.io instance is up, running, and responsive). After initiating a pump client in PyPump, I retrieve my profile using the pump.me approach. I get back a valid Person object, but it contains only 1 entry in its .links data member. You can easily reproduce this in PyPump 0.7 as follows:

<code>
python3 /usr/local/bin/pypump-shell steve@hub.polari.us --log=debug

-> Setting up PyPump  DEBUG:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): hub.polari.us
DEBUG:requests.packages.urllib3.connectionpool:https://hub.polari.us:443 "POST /api/client/register HTTP/1.1" 200 115
DEBUG:pypump.client:Client registration recieved: XXXX YYYY 0
Welcome to the PyPump Shell,
We have setup some useful objects for you:

+--------+-------------------------------------------------+----------+
| Type   | Representation                                  | Variable | 
+--------+-------------------------------------------------+----------+
| PyPump | <pypump.pypump.PyPump object at 0x7fe7b7e4c160> | pump     | 
+--------+-------------------------------------------------+----------+

If you need help please visit our docs:
https://pypump.readthedocs.org/en/latest

In [1]: pump.me
Out[1]: <Person: steve@hub.polari.us>

In [2]: pump.me.links
Out[2]: {'self': 'https://hub.polari.us/api/user/steve/profile'}

In [3]: pump.me.outbox
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
/usr/local/lib/python3.4/dist-packages/PyPump-0.7-py3.4.egg/EGG-INFO/scripts/pypump-shell in <module>()
----> 1 pump.me.outbox

/usr/local/lib/python3.4/dist-packages/PyPump-0.7-py3.4.egg/pypump/models/person.py in outbox(self)
     65             pypumptest2 deleted a note
     66         """
---> 67         self._outbox = self._outbox or Outbox(self.links['activity-outbox'], pypump=self._pump)
     68         return self._outbox
     69 

KeyError: 'activity-outbox'
</code>

Any ideas how to proceed debuggin this from here?
