### ISSUE TITLE
Can't use with https-only instance

### ISSUE THREAD

**Issue by mrvdb** [xray7224/PyPump#140]
If the only way to use an instance is through a `https` connection, the line

https://github.com/xray7224/PyPump/blob/master/pypump/pypump.py#L388

prevents proper functioning. The code seems to expect a server to talk `http` possibly redirecting to `https`

**Comment by moggers87** [comment]
Oh my, that doesn't look right at all. Thanks for the report.

**Comment by moggers87** [comment]
I've started work on this on branch `140-https-only-support`. Looks like we're doing a lot of weird stuff like falling back to HTTP randomly.
