### ISSUE TITLE
Make 0.7 release

### ISSUE THREAD

**Issue by dper** [xray7224/PyPump#144]
An important bug affecting new logins when using Python3 was fixed shortly after 0.6 was released last year. There have been no releases since 0.6. For PyPi installations, this is awkward because the only workaround involves using both Python2 and Python 3, which is confusing to new users of PyPump and other programs that depend on it, like PumpTweet.

It would be cool to get 0.7 released fairly soon, unless there are significant issues with MASTER now. Are there?

**Comment by moggers87** [comment]
https://github.com/xray7224/PyPump/milestones/0.7

I'd like to see a few more of these closed before I start bugging Jess about doing another release.

**Comment by dper** [comment]
The specific issue that I would like a release for is https://github.com/xray7224/PyPump/issues/127. That was fixed a year ago, but no release since then. For PumpTweet to install cleanly, a new PyPump release is needed.

If I may speak selfishly for a moment, in the best case for me in my own project... Looking at those milestones, if those are bugs that existed in 0.6 and still exist now, or if they are desired new features, they could be pushed back to 0.8 without causing any problems. If any bugs were added after 0.6 and are show-stoppers, those would be release-blockers.

Alternately, if we think it will take some time to check off those milestones, but we predict it happening by [insert approximate month here], that information would be quite useful. Then I could plan out some of my own development time. (In any case, PyPump is very handy and easy to use, and thanks to the developers for developing it.)

**Comment by xray7224** [comment]
I agree, I don't have much time so the best I can give you as a release date is Sunday the 26th of this month.

**Comment by moggers87** [comment]
@dper https://microca.st/moggers87/note/g-yKR83XSeuw6xsyPPED4Q

**Comment by moggers87** [comment]
Done.
