### ISSUE TITLE
Image.original is not set if data["fullImage"] does not exist

### ISSUE THREAD

**Issue by kabniel** [xray7224/PyPump#145]
We check if we should save data["image"] to Image.original by checking if Image.original already exist, if it does we save to Image.thumbnail instead. The problem is that Image.original gets created (set to None) on Image init so it will always exist and the check will always fail, we could check if it's True instead.

Mentioned in https://github.com/dper/pumptweet/issues/32

**Comment by dper** [comment]
Wonderful. Thanks!!
