### ISSUE TITLE
Documentation has disappeared

### ISSUE THREAD

**Issue by skellat** [xray7224/PyPump#155]
While attempting to use the packaged version of pypump-shell in Xubuntu 18.04, I found that the documentation previously referenced appears to no longer be posted.  Is there a backup anywhere?

**Comment by moggers87** [comment]
It's available in the repository, but I don't know why it's gone from RTDs.

@xray7224 or @kabniel might know

**Comment by moggers87** [comment]
Mystery solved: @xray7224 deleted her RTD account
