### ISSUE TITLE
.serialize() should return JSON not a dict()

### ISSUE THREAD

**Issue by moggers87** [xray7224/PyPump#82]
It should allow optional pretty printing (something like `indent=4` etc. too

**Comment by polypmer** [comment]
For printing the dict as something pretty *like* json, maybe <code>.serialize()</code> could return a string (from a json.dump of the dictionary)? Something like this:

<pre>
import json

activity = me.inbox.major[1]
message = activity.obj

def output_json(activity): #input message object
    the_dict = activity.serialize()
    the_json = json.dumps(the_dict, sort_keys=True, 
                          indent=4, separators=(',', ': '))
    print the_json
    
output_json(message)
</pre>

which prints in json format (but returns a str...):
<pre>
{
    "bcc": [],
    "bto": [],
    "cc": [
        {
            "id": "https://microca.st/api/user/polypmer/followers",
            "objectType": "collection"
        }
    ],
    "object": {
        "content": "PyPump sure is pretty",
        "objectType": "note"
    },
    "to": [],
    "verb": "post"
}
</pre>
#### In any case, the tutorial (incorrectly?) instructs us to try this:
<pre>
>>> output = message.serialize(indent=4)
>>> print(output)
</pre>
When printing message.serialize(), it outputs a block of text
<pre>
{'to': [], 'verb': 'post', 'cc': [{'id': u'https://microca.st/api/user/polypmer/followers', 'objectType': 'collection'}], 'bto': [], 'object': {'content': u'PyPump sure is pretty', 'objectType': u'note'}, 'bcc': []}
</pre>
When running (without print) message.serialize(), it outputs something a bit more pretty (a dict)
<pre>
{'bcc': [],
 'bto': [],
 'cc': [{'id': u'https://microca.st/api/user/polypmer/followers',
   'objectType': 'collection'}],
 'object': {'content': u'PyPump sure is pretty', 'objectType': u'note'},
 'to': [],
 'verb': 'post'}
</pre>

**Comment by moggers87** [comment]
Can anyone remember why I reported this? While `Addressable.serialize` and friends don't serialize to JSON, subclasses want the return data to be mutable. Serialization to JSON happens in `PyPump.request` at the last possible moment.

**Comment by kabniel** [comment]
Maybe because of https://github.com/xray7224/PyPump/blob/master/pypump/models/note.py#L51 ?

**Comment by moggers87** [comment]
Yeah, I think you're right. Closing issue.
